---
  title: "Business Analytics Projects"
---
---
## Similarity based learning - Project 2 
In this project, I have focused on text mining using similarity based learning techniques. 

<script src="https://gist.github.com/shwarajtuse/c3242abae2ddf3b59bb8811444223549.js"></script>


## Similarity based learning - Project 1
In this project, I have studied Similarity-based approaches to machine learning. It simply looks at what has worked well in the past and predict the same thing again. The fundamental concepts required to build a system based on this idea are feature spaces and measures of similarity. Further I have implemented the nearest neighbor algorithm which looks at the text classification using similarity based learning. I also learnt about data normalization and feature selection in the context of similarity-based learning.

<script src="https://gist.github.com/shwarajtuse/ab022d8b6c7693d2857734f02bc86488.js"></script>

## Infornmation based learning
In this project, I workd on decision trees to understand fundamentals of information-based machine learning. I understood the measures of information content viz.-2 log likelihood (entropy). KL divergence, gini index, information gain etc. Later I studied ID3 algorithm to induce decision tree in different data types, right fitting the model on data using tree pruning and finally ensembles to improve model performance.


<script src="https://gist.github.com/shwarajtuse/9bb4930a55edc332fd760b613e9ce151.js"></script>

## Data visualization and Exploratory data analysis
In this project, I have performed univariate and bivariate analysis on all the variables in the data. I have used data visualization techniques to further analyze the data. It is a particularly efficient way of communicating when the data is numerous.

<script src="https://gist.github.com/shwarajtuse/ca8b9cb074b225be224c41ea8c00ab5a.js"></script>

## Exploratory data analysis 
In this project, I have studied the data by performing exploratory data analysis on it. 

<script src="https://gist.github.com/shwarajtuse/8656b44a13360ff93a2bd11dac5777bd.js"></script>